import * as React from 'react'
import { FunctionComponent, memo, useMemo } from 'react'
import { cloneContent, FlatContent } from '@editor/model'
import { ContentYjsStoreContextProvider, readOnlyStore } from './store.tsx'
import { Box } from '@mui/material'
import { ContentInputViewReferencedSchema } from './index.tsx'
